services:
  ai-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ai-service
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "3003:3000"       # host:container
    networks:
      - pdinfinita_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s

networks:
  pdinfinita_network:
    external: true
