services:
  ai-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ai-service
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "3003:3000"
    networks:
      - pdinfinita_network

networks:
  pdinfinita_network:
    external: true
